const questionBank = {
  // Section A: Letters & Phonics (Original + New = ~40)
  sectionA: [
    { q: 'ما هذا الحرف؟', display: 'A', options: ['A', 'B', 'C', 'D'], answer: 'A', type: 'choice' },
    { q: 'ما هذا الحرف؟', display: 'B', options: ['A', 'B', 'P', 'R'], answer: 'B', type: 'choice' },
    { q: 'ما صوت حرف "C" في كلمة "Cat"؟', display: '🐱', options: ['/k/', '/s/', '/ch/', '/g/'], answer: '/k/', type: 'choice' },
    { q: 'أي حرف يبدأ به كلمة "Dog"؟', display: '🐕', options: ['B', 'D', 'P', 'G'], answer: 'D', type: 'choice' },
    { q: 'ما هذا الحرف؟', display: 'M', options: ['N', 'M', 'W', 'V'], answer: 'M', type: 'choice' },
    { q: 'اكتب الحرف الأول من كلمة "Sun"', display: '☀️', answer: 'S', type: 'typing' },
    { q: 'اكتب الحرف الأول من كلمة "Tree"', display: '🌳', answer: 'T', type: 'typing' },
    { q: 'أي كلمة تبدأ بحرف "B"؟', display: '', options: ['🍎 Apple', '🍌 Banana', '🍊 Orange', '🍇 Grape'], answer: '🍌 Banana', type: 'choice' },
    { q: 'ما الحرف الذي يأتي بعد "A"؟', display: 'A ← ?', options: ['C', 'B', 'D', 'E'], answer: 'B', type: 'choice' },
    { q: 'أي منهم حرف متحرك (vowel)؟', display: '', options: ['B', 'C', 'E', 'D'], answer: 'E', type: 'choice' },
    { q: 'اكتب الحروف الناقصة: A__le', display: '🍎', answer: 'PP', type: 'typing' },
    { q: 'ما صوت "SH"؟', display: '🤫', options: ['/sh/', '/s/', '/ch/', '/th/'], answer: '/sh/', type: 'choice' },
    { q: 'اختر حرف "a" أو "an" الصحيح: ___ apple', display: '🍎', options: ['a', 'an'], answer: 'an', type: 'choice' },
    { q: 'اختر حرف "a" أو "an" الصحيح: ___ dog', display: '🐕', options: ['a', 'an'], answer: 'a', type: 'choice' },
    { q: 'ما هذا الحرف؟', display: 'G', options: ['C', 'G', 'J', 'O'], answer: 'G', type: 'choice' },
    { q: 'ما صوت حرف "H" في كلمة "Hat"؟', display: '🎩', options: ['/h/', '/w/', '/f/', '/p/'], answer: '/h/', type: 'choice' },
    { q: 'اكتب الحرف الناقص: Z__bra', display: '🦓', answer: 'E', type: 'typing' },
    { q: 'أي كلمة تبدأ بحرف "F"؟', display: '', options: ['🐸 Frog', '🐶 Dog', '🐱 Cat', '🦁 Lion'], answer: '🐸 Frog', type: 'choice' },
    { q: 'ما الحرف الصغير (small) لـ "R"؟', display: 'R', options: ['r', 'n', 'm', 's'], answer: 'r', type: 'choice' },
    { q: 'ما الحرف الكبير (capital) لـ "q"؟', display: 'q', options: ['Q', 'P', 'O', 'G'], answer: 'Q', type: 'choice' },
    // New Questions Section A
    { q: 'ما الحرف الذي يأتي بعد "D"؟', display: 'D ← ?', options: ['E', 'F', 'C', 'H'], answer: 'E', type: 'choice' },
    { q: 'اكتب الحرف الأول من كلمة "Fish"', display: '🐟', answer: 'F', type: 'typing' },
    { q: 'أي كلمة تبدأ بحرف "S"؟', display: '☀️', options: ['Sun', 'Moon', 'Rain', 'Car'], answer: 'Sun', type: 'choice' },
    { q: 'ما الحرف الكبير (capital) لـ "m"؟', display: 'm', options: ['N', 'M', 'W', 'U'], answer: 'M', type: 'choice' },
    { q: 'ما الحرف الصغير (small) لـ "H"؟', display: 'H', options: ['h', 'n', 'b', 'k'], answer: 'h', type: 'choice' },
    { q: 'أي منهم ليس حرف متحرك (consonant)؟', display: '', options: ['A', 'E', 'B', 'I'], answer: 'B', type: 'choice' },
    { q: 'اكتب الحرف الناقص: Li__n', display: '🦁', answer: 'O', type: 'typing' },
    { q: 'ما صوت حرف "S" في كلمة "Snake"؟', display: '🐍', options: ['/s/', '/z/', '/sh/', '/k/'], answer: '/s/', type: 'choice' },
    { q: 'ما هذا الحرف؟', display: 'Z', options: ['S', 'Z', 'N', 'X'], answer: 'Z', type: 'choice' },
    { q: 'أي كلمة تبدأ بحرف "P"؟', display: '', options: ['Pen', 'Hen', 'Ten', 'Den'], answer: 'Pen', type: 'choice' },
    { q: 'ما هذا الحرف؟', display: 'K', options: ['L', 'R', 'K', 'H'], answer: 'K', type: 'choice' },
    { q: 'ما صوت حرف "P" في كلمة "Pen"؟', display: '🖊️', options: ['/p/', '/b/', '/f/', '/v/'], answer: '/p/', type: 'choice' },
    { q: 'اكتب الحرف الأول من كلمة "Egg"', display: '🥚', answer: 'E', type: 'typing' },
    { q: 'أي حرف يبدأ به كلمة "Moon"؟', display: '🌙', options: ['M', 'N', 'O', 'S'], answer: 'M', type: 'choice' },
    { q: 'ما الحرف الذي يأتي قبل "C"؟', display: '? ← C', options: ['A', 'B', 'D', 'E'], answer: 'B', type: 'choice' },
    { q: 'اختر حرف "a" أو "an" الصحيح: ___ orange', display: '🍊', options: ['a', 'an'], answer: 'an', type: 'choice' },
    { q: 'اكتب الحرف الناقص: B__rd', display: '🐦', answer: 'I', type: 'typing' },
    { q: 'ما هذا الحرف؟', display: 'Y', options: ['V', 'U', 'Y', 'T'], answer: 'Y', type: 'choice' }
  ],

  // Section B: Pronunciation (Original + New = ~35)
  sectionB: [
    { q: 'أي كلمة تبدأ بصوت /sh/؟', display: '🤫', options: ['Sun', 'Ship', 'Sit', 'Soup'], answer: 'Ship', type: 'choice' },
    { q: 'أي كلمة لها نفس صوت حرف العلة في "Go"؟', display: '', options: ['Got', 'Boat', 'Good', 'Gone'], answer: 'Boat', type: 'choice' },
    { q: 'أي كلمة تتناغم مع "Cat"؟', display: '🐱', options: ['Dog', 'Hat', 'Cup', 'Sun'], answer: 'Hat', type: 'choice' },
    { q: 'كم مقطع صوتي في "Banana"؟', display: '🍌', options: ['2', '3', '4', '1'], answer: '3', type: 'choice' },
    { q: 'أي كلمة لها نفس صوت حرف العلة في "Bee"؟', display: '🐝', options: ['Bed', 'See', 'Bit', 'But'], answer: 'See', type: 'choice' },
    { q: 'أي كلمة تنتهي بصوت /t/؟', display: '', options: ['Car', 'Cat', 'Cow', 'Can'], answer: 'Cat', type: 'choice' },
    { q: 'أي كلمة تتناغم مع "Blue"؟', display: '🔵', options: ['Black', 'Shoe', 'Bread', 'Book'], answer: 'Shoe', type: 'choice' },
    { q: 'أي كلمة تبدأ بصوت /th/؟', display: '', options: ['Tree', 'Three', 'Free', 'See'], answer: 'Three', type: 'choice' },
    { q: 'أي كلمة لها صوت طويل (Long A)؟', display: '', options: ['Cat', 'Cake', 'Hat', 'Map'], answer: 'Cake', type: 'choice' },
    { q: 'حدد الكلمة المختلفة في النطق:', display: '', options: ['Go', 'No', 'So', 'Do'], answer: 'Do', type: 'choice' },
    // New Questions Section B
    { q: 'أي كلمة تتناغم مع "Ball"؟', display: '⚽', options: ['Tall', 'Bell', 'Full', 'Tell'], answer: 'Tall', type: 'choice' },
    { q: 'أي كلمة تبدأ بصوت /f/؟', display: '', options: ['Van', 'Fan', 'Pan', 'Man'], answer: 'Fan', type: 'choice' },
    { q: 'كم مقطع صوتي في "Elephant"؟', display: '🐘', options: ['2', '3', '4', '1'], answer: '3', type: 'choice' },
    { q: 'أي كلمة تنتهي بصوت /k/؟', display: '', options: ['Bag', 'Duck', 'Dog', 'Pig'], answer: 'Duck', type: 'choice' },
    { q: 'أي كلمة تتناغم مع "Sun"؟', display: '☀️', options: ['Run', 'Man', 'Pen', 'Ten'], answer: 'Run', type: 'choice' },
    { q: 'أي كلمة لها صوت طويل (Long I)؟', display: '', options: ['Sit', 'Bike', 'Bit', 'Hit'], answer: 'Bike', type: 'choice' },
    { q: 'أي كلمة تبدأ بصوت /ch/؟', display: '', options: ['Ship', 'Chair', 'Shoe', 'Share'], answer: 'Chair', type: 'choice' },
    { q: 'حدد الكلمة المختلفة في النطق:', display: '', options: ['Car', 'Bar', 'Far', 'Cat'], answer: 'Cat', type: 'choice' },
    { q: 'أي كلمة تتناغم مع "Pen"؟', display: '🖊️', options: ['Pan', 'Ten', 'Tin', 'Tan'], answer: 'Ten', type: 'choice' },
    { q: 'أي كلمة تبدأ بصوت /b/؟', display: '', options: ['Pen', 'Ben', 'Ten', 'Den'], answer: 'Ben', type: 'choice' },
    { q: 'أي كلمة لها نفس صوت حرف العلة في "Book"؟', display: '📚', options: ['Look', 'Door', 'Floor', 'More'], answer: 'Look', type: 'choice' },
    { q: 'كم مقطع صوتي في "Cat"؟', display: '🐱', options: ['1', '2', '3', '4'], answer: '1', type: 'choice' },
    { q: 'أي كلمة تتناغم مع "Red"؟', display: '🔴', options: ['Bed', 'Bad', 'Sad', 'Dad'], answer: 'Bed', type: 'choice' },
    { q: 'أي كلمة تنتهي بصوت /s/؟', display: '', options: ['Bus', 'Buzz', 'Bug', 'Bun'], answer: 'Bus', type: 'choice' },
    { q: 'أي كلمة لها صوت قصير (Short O)؟', display: '', options: ['Hot', 'Hope', 'Home', 'Bone'], answer: 'Hot', type: 'choice' },
    { q: 'أي كلمة تبدأ بصوت /j/؟', display: '', options: ['Goat', 'Jar', 'Car', 'Far'], answer: 'Jar', type: 'choice' },
    { q: 'أي كلمة تتناغم مع "Fish"؟', display: '🐟', options: ['Dish', 'Dash', 'Wash', 'Cash'], answer: 'Dish', type: 'choice' },
    { q: 'كم مقطع صوتي في "Computer"؟', display: '💻', options: ['2', '3', '4', '1'], answer: '3', type: 'choice' },
    { q: 'أي كلمة لها صوت طويل (Long O)؟', display: '', options: ['Pop', 'Top', 'Hope', 'Pot'], answer: 'Hope', type: 'choice' },
    { q: 'أين النبر (Stress) في كلمة "Teacher"؟', display: '👩‍🏫', options: ['TEA-cher', 'tea-CHER'], answer: 'TEA-cher', type: 'choice' }
  ],

  // Section C: Listening (Original + New = ~35)
  sectionC: [
    { q: 'استمع بعناية ثم اختر الإجابة الصحيحة 🎧', display: '🍎', word: 'Apple', options: ['Apple', 'Orange', 'Banana', 'Grape'], answer: 'Apple', type: 'choice' },
    { q: 'استمع بعناية ثم اختر الرقم الذي تسمعه 🎧', display: '🔢', word: 'Nine', options: ['Five', 'Nine', 'Six', 'Eight'], answer: 'Nine', type: 'choice' },
    { q: 'استمع بعناية ثم اختر اللون 🎧', display: '🔴', word: 'Red', options: ['Blue', 'Green', 'Red', 'Yellow'], answer: 'Red', type: 'choice' },
    { q: 'استمع بعناية ثم اختر الإجابة 🎧', display: '📚', word: 'Book', options: ['Book', 'Bag', 'Pencil', 'Phone'], answer: 'Book', type: 'choice' },
    { q: 'استمع بعناية ثم اختر الحيوان 🎧', display: '🐘', word: 'Big elephant', options: ['Ant', 'Elephant', 'Dog', 'Cat'], answer: 'Elephant', type: 'choice' },
    { q: 'استمع واختر اليوم الصحيح 🎧', display: '📅', word: 'Monday', options: ['Monday', 'Tuesday', 'Friday', 'Sunday'], answer: 'Monday', type: 'choice' },
    { q: 'استمع بعناية ثم اختر الكلمة 🎧', display: '👨‍🏫', word: 'Teacher', options: ['Teacher', 'Doctor', 'Chef', 'Pilot'], answer: 'Teacher', type: 'choice' },
    { q: 'استمع بعناية ثم اختر الفعل 🎧', display: '🤸', word: 'I like to jump', options: ['Run', 'Jump', 'Walk', 'Climb'], answer: 'Jump', type: 'choice' },
    { q: 'استمع ثم اختر الصورة الصحيحة 🎧', display: '😊', word: 'Happy', options: ['Happy', 'Sad', 'Angry', 'Sleepy'], answer: 'Happy', type: 'choice' },
    { q: 'استمع واكتب الكلمة التي تسمعها 🎧', display: '🦁', word: 'Lion', answer: 'LION', type: 'typing' },
    // New Questions Section C
    { q: 'استمع واختر الحيوان 🎧', display: '🐕', word: 'Dog', options: ['Cat', 'Dog', 'Cow', 'Horse'], answer: 'Dog', type: 'choice' },
    { q: 'استمع واختر الرقم 🎧', display: '1️⃣', word: 'One', options: ['1', '2', '3', '4'], answer: '1', type: 'choice' },
    { q: 'استمع واختر اللون 🎧', display: '🟢', word: 'Green', options: ['Red', 'Blue', 'Green', 'Black'], answer: 'Green', type: 'choice' },
    { q: 'استمع للكلمة واختر الصورة 🎧', display: '🚗', word: 'Car', options: ['Car', 'Bus', 'Bike', 'Plane'], answer: 'Car', type: 'choice' },
    { q: 'استمع للعمل 🎧', display: '👨‍⚕️', word: 'Doctor', options: ['Doctor', 'Teacher', 'Police', 'Fireman'], answer: 'Doctor', type: 'choice' },
    { q: 'استمع واختر الفاكهة 🎧', display: '🍌', word: 'Banana', options: ['Apple', 'Banana', 'Grape', 'Lemon'], answer: 'Banana', type: 'choice' },
    { q: 'استمع واختر العضو 🎧', display: '🖐️', word: 'Hand', options: ['Leg', 'Hand', 'Eye', 'Ear'], answer: 'Hand', type: 'choice' },
    { q: 'استمع واختر الرقم 🎧', display: '7️⃣', word: 'Seven', options: ['6', '7', '8', '9'], answer: '7', type: 'choice' },
    { q: 'استمع واكتب الكلمة 🎧', display: '🐱', word: 'Cat', answer: 'CAT', type: 'typing' },
    { q: 'استمع واختر الشكل 🎧', display: '⭐', word: 'Star', options: ['Star', 'Heart', 'Square', 'Circle'], answer: 'Star', type: 'choice' },
    { q: 'استمع واختر الفعل 🎧', display: '🏃', word: 'Run', options: ['Run', 'Sleep', 'Eat', 'Read'], answer: 'Run', type: 'choice' },
    { q: 'استمع واختر المكان 🎧', display: '🏫', word: 'School', options: ['School', 'Home', 'Hospital', 'Park'], answer: 'School', type: 'choice' },
    { q: 'استمع للكلمة 🎧', display: '🐟', word: 'Fish', options: ['Fish', 'Bird', 'Frog', 'Turtle'], answer: 'Fish', type: 'choice' },
    { q: 'استمع واختر اللون 🎧', display: '🔵', word: 'Blue', options: ['Green', 'Blue', 'Yellow', 'Purple'], answer: 'Blue', type: 'choice' },
    { q: 'استمع للمشاعر 🎧', display: '😢', word: 'Sad', options: ['Happy', 'Sad', 'Angry', 'Scared'], answer: 'Sad', type: 'choice' },
    { q: 'استمع واكتب الكلمة 🎧', display: '🖊️', word: 'Pen', answer: 'PEN', type: 'typing' },
    { q: 'استمع واختر 🎧', display: '🥛', word: 'Milk', options: ['Milk', 'Juice', 'Water', 'Tea'], answer: 'Milk', type: 'choice' },
    { q: 'استمع واختر الفرد من العائلة 🎧', display: '👩', word: 'Mother', options: ['Father', 'Mother', 'Baby', 'Grandpa'], answer: 'Mother', type: 'choice' },
    { q: 'استمع واختر الرقم 🎧', display: '🔟', word: 'Ten', options: ['10', '2', '5', '8'], answer: '10', type: 'choice' },
    { q: 'استمع واختر الطقس 🎧', display: '☀️', word: 'Sunny', options: ['Sunny', 'Rainy', 'Snowy', 'Windy'], answer: 'Sunny', type: 'choice' }
  ],

  // Section D: Reading (Original + New = ~45)
  sectionD: [
    { q: 'Read: "The cat is big." What is big?', display: 'The cat is big. 🐱', options: ['Dog', 'Cat', 'Bird', 'Fish'], answer: 'Cat', type: 'choice' },
    { q: 'Read: "I have two apples." How many apples?', display: 'I have two apples. 🍎🍎', options: ['1', '2', '3', '4'], answer: '2', type: 'choice' },
    { q: 'Read: "She is a girl." Is it a boy or girl?', display: 'She is a girl. 👧', options: ['Boy', 'Girl', 'Man', 'Woman'], answer: 'Girl', type: 'choice' },
    { q: 'Read: "The sun is yellow." What color is the sun?', display: 'The sun is yellow. ☀️', options: ['Red', 'Blue', 'Yellow', 'Green'], answer: 'Yellow', type: 'choice' },
    { q: 'Read: "My name is Tom." What is his name?', display: 'My name is Tom. 👦', options: ['Tim', 'Tom', 'Sam', 'Jim'], answer: 'Tom', type: 'choice' },
    { q: 'Read: "Dogs can run fast." What can dogs do?', display: 'Dogs can run fast. 🐕💨', options: ['Fly', 'Swim', 'Run', 'Jump'], answer: 'Run', type: 'choice' },
    { q: 'Read: "It is cold in winter." When is it cold?', display: 'It is cold in winter. ❄️', options: ['Summer', 'Winter', 'Spring', 'Fall'], answer: 'Winter', type: 'choice' },
    { q: 'Read: "I like pizza." What does he like?', display: 'I like pizza. 🍕', options: ['Burger', 'Pizza', 'Salad', 'Soup'], answer: 'Pizza', type: 'choice' },
    { q: 'Read: "Birds fly in the sky." Where do birds fly?', display: 'Birds fly in the sky. 🐦☁️', options: ['Water', 'Ground', 'Sky', 'Tree'], answer: 'Sky', type: 'choice' },
    { q: 'Read: "Mom cooks food." Who cooks?', display: 'Mom cooks food. 👩‍🍳', options: ['Dad', 'Mom', 'Sister', 'Brother'], answer: 'Mom', type: 'choice' },
    { q: 'Choose the correct sentence:', display: '🚗', options: ['It is a car.', 'It is a cat.', 'It is a cup.', 'It is a cap.'], answer: 'It is a car.', type: 'choice' },
    { q: 'Complete: Fish live in the ___ ', display: '🐟', options: ['sky', 'water', 'land', 'tree'], answer: 'water', type: 'choice' },
    // New Questions Section D
    { q: 'Read: "I am eleven years old." How old?', display: '🎂', options: ['5', '6', '11', '8'], answer: '11', type: 'choice' },
    { q: 'Read: "The grass is green." What color?', display: '🌿', options: ['Red', 'Green', 'Blue', 'Yellow'], answer: 'Green', type: 'choice' },
    { q: 'Choose the correct sentence:', display: '🍎', options: ['This is an apple.', 'This is a banana.', 'This is a car.', 'This is a dog.'], answer: 'This is an apple.', type: 'choice' },
    { q: 'Complete: Monkeys like to eat ___', display: '🐒', options: ['bananas', 'pizza', 'cars', 'books'], answer: 'bananas', type: 'choice' },
    { q: 'Read: "He plays football." What does he play?', display: '⚽', options: ['Tennis', 'Football', 'Swimming', 'Running'], answer: 'Football', type: 'choice' },
    { q: 'Read: "The elephant is big." How is the elephant?', display: '🐘', options: ['Small', 'Big', 'Fast', 'Tall'], answer: 'Big', type: 'choice' },
    { q: 'Complete: We sleep in the ___', display: '🛌', options: ['kitchen', 'bathroom', 'bedroom', 'garden'], answer: 'bedroom', type: 'choice' },
    { q: 'Read: "She has long hair." How is her hair?', display: '👩', options: ['Short', 'Long', 'Red', 'None'], answer: 'Long', type: 'choice' },
    { q: 'Choose the odd one out:', display: '', options: ['Apple', 'Banana', 'Car', 'Orange'], answer: 'Car', type: 'choice' },
    { q: 'Read: "I go to school by bus." How does he go?', display: '🚌', options: ['Walk', 'Car', 'Bus', 'Bike'], answer: 'Bus', type: 'choice' },
    { q: 'Complete: A cat says ___', display: '🐱', options: ['moo', 'woof', 'meow', 'quack'], answer: 'meow', type: 'choice' },
    { q: 'Read: "My father is a doctor." What is his job?', display: '👨‍⚕️', options: ['Teacher', 'Doctor', 'Engineer', 'Police'], answer: 'Doctor', type: 'choice' },
    { q: 'Which animal can fly?', display: '', options: ['Dog', 'Bird', 'Cat', 'Fish'], answer: 'Bird', type: 'choice' },
    { q: 'Read: "It is hot in summer." How is the weather?', display: '☀️', options: ['Cold', 'Hot', 'Rainy', 'Snowy'], answer: 'Hot', type: 'choice' },
    { q: 'What is the opposite of "Happy"?', display: '😊', options: ['Sad', 'Good', 'Nice', 'Fine'], answer: 'Sad', type: 'choice' },
    { q: 'Complete: Rabbits have long ___', display: '🐰', options: ['ears', 'noses', 'tails', 'eyes'], answer: 'ears', type: 'choice' },
    { q: 'Read: "Give me the red pen." Which pen?', display: '🖍️', options: ['Blue', 'Yellow', 'Red', 'Black'], answer: 'Red', type: 'choice' },
    { q: 'What do we wear on our feet?', display: '👟', options: ['Hat', 'Shoes', 'Shirt', 'Gloves'], answer: 'Shoes', type: 'choice' },
    { q: 'Read: "Close the door." What to do?', display: '🚪', options: ['Open', 'Close', 'Break', 'Clean'], answer: 'Close', type: 'choice' },
    { q: 'Complete: Ice cream is ___', display: '🍦', options: ['hot', 'cold', 'spicy', 'salty'], answer: 'cold', type: 'choice' },
    { q: 'Choose the sentence:', display: '👶', options: ['He is a man.', 'He is a baby.', 'She is a woman.', 'It is a dog.'], answer: 'He is a baby.', type: 'choice' },
    { q: 'Read: "The car is blue." What color is it?', display: '🚙', options: ['Red', 'Blue', 'Green', 'Black'], answer: 'Blue', type: 'choice' },
    // Advanced Reading Questions (Inferencing & Comprehension) - For Level 6 Challenge
    { q: 'Read: "Tom felt sick yesterday so he stayed in bed." Why did Tom stay in bed?', options: ['He was lazy', 'He was tired', 'He was ill', 'He was hungry'], answer: 'He was ill', type: 'choice' },
    { q: 'Read: "Sarah needs flour, eggs, and sugar." What is she likely making?', options: ['Soup', 'Salad', 'Cake', 'Pizza'], answer: 'Cake', type: 'choice' },
    { q: 'Read: "The streets are wet and everyone has umbrellas." What is happening?', options: ['It is snowing', 'It is raining', 'It is sunny', 'It is windy'], answer: 'It is raining', type: 'choice' },
    { q: 'Read: "Jack put on his helmet and knee pads." What will he do?', options: ['Sleep', 'Swim', 'Ride a bike', 'Read a book'], answer: 'Ride a bike', type: 'choice' },
    { q: 'Read: "The room was very dark until I turned this on." What is it?', options: ['Fan', 'Light', 'Radio', 'Chair'], answer: 'Light', type: 'choice' },
    { q: 'Read: "You use me to cut paper." What am I?', options: ['Glue', 'Scissors', 'Ruler', 'Pencil'], answer: 'Scissors', type: 'choice' },
    { q: 'Read: "I have a face and hands but no body." What am I?', options: ['Clock', 'Cat', 'Door', 'Ball'], answer: 'Clock', type: 'choice' },
    { q: 'Read: "Lisa went to the dock and got on a large vessel." Where is she?', options: ['On a train', 'On a plane', 'On a ship', 'On a bus'], answer: 'On a ship', type: 'choice' },
    { q: 'Read: "He wears a white coat and helps sick people." Who is he?', options: ['Doctor', 'Chef', 'Pilot', 'Artist'], answer: 'Doctor', type: 'choice' },
    { q: 'Read: "It is a fruit. It is yellow and curved." What is it?', options: ['Apple', 'Banana', 'Orange', 'Grape'], answer: 'Banana', type: 'choice' }
  ],

  // Section E: Writing (Original + New = ~35)
  sectionE: [
    { q: 'اكتب الكلمة لهذا الحيوان:', display: '🐱', answer: 'CAT', type: 'typing' },
    { q: 'اكتب الكلمة لهذه الفاكهة:', display: '🍎', answer: 'APPLE', type: 'typing' },
    { q: 'اكتب عكس كلمة "Big":', display: '', oppositeWord: 'Big', answer: 'SMALL', type: 'typing', isOpposite: true },
    { q: 'اكتب اللون:', display: '🔴', answer: 'RED', type: 'typing' },
    { q: 'اكتب الرقم:', display: '5️⃣', answer: 'FIVE', type: 'typing' },
    { q: 'اكتب الكلمة لهذا الحيوان:', display: '🐕', answer: 'DOG', type: 'typing' },
    { q: 'اكتب عكس كلمة "Hot":', display: '', oppositeWord: 'Hot', answer: 'COLD', type: 'typing', isOpposite: true },
    { q: 'اكتب اليوم الذي يأتي بعد الاثنين:', display: 'Monday ← ?', answer: 'TUESDAY', type: 'typing' },
    { q: 'رتب الكلمات لتكوين جملة: (is / blue / sky / The)', display: '☁️', isScrambled: true, options: ['The sky is blue', 'Blue sky is the', 'The blue sky is', 'Sky is the blue'], answer: 'The sky is blue', type: 'choice' },
    { q: 'اكتب جمع كلمة "Boy":', display: '👦👦', answer: 'BOYS', type: 'typing' },
    { q: 'اكتب اسم هذا الشكل:', display: '⭐', answer: 'STAR', type: 'typing' },
    { q: 'اكتب عكس كلمة "Happy":', display: '', oppositeWord: 'Happy', answer: 'SAD', type: 'typing', isOpposite: true },
    // New Questions Section E
    { q: 'اكتب الكلمة:', display: '🚗', answer: 'CAR', type: 'typing' },
    { q: 'اكتب الكلمة:', display: '🚌', answer: 'BUS', type: 'typing' },
    { q: 'اكتب عكس كلمة "Up":', display: '', oppositeWord: 'Up', answer: 'DOWN', type: 'typing', isOpposite: true },
    { q: 'اكتب الكلمة:', display: '🌞', answer: 'SUN', type: 'typing' },
    { q: 'اكتب الرقم:', display: '🔟', answer: 'TEN', type: 'typing' },
    { q: 'اكتب الكلمة:', display: '🐟', answer: 'FISH', type: 'typing' },
    { q: 'اكتب عكس كلمة "Day":', display: '', oppositeWord: 'Day', answer: 'NIGHT', type: 'typing', isOpposite: true },
    { q: 'اكتب جمع كلمة "Book":', display: '📚', answer: 'BOOKS', type: 'typing' },
    { q: 'اكتب الكلمة:', display: '🖊️', answer: 'PEN', type: 'typing' },
    { q: 'اكتب الكلمة:', display: '🥚', answer: 'EGG', type: 'typing' },
    { q: 'رتب الكلمات: (name / is / My / Ahmed)', display: '🧒', isScrambled: true, options: ['My name is Ahmed', 'Ahmed is name My', 'Name My is Ahmed', 'is name My Ahmed'], answer: 'My name is Ahmed', type: 'choice' },
    { q: 'اكتب عكس كلمة "Good":', display: '', oppositeWord: 'Good', answer: 'BAD', type: 'typing', isOpposite: true },
    { q: 'اكتب الكلمة:', display: '🧢', answer: 'HAT', type: 'typing' },
    { q: 'اكتب الكلمة:', display: '🛏️', answer: 'BED', type: 'typing' },
    { q: 'اكتب الرقم:', display: '1️⃣', answer: 'ONE', type: 'typing' },
    { q: 'اكتب عكس كلمة "Boy":', display: '', oppositeWord: 'Boy', answer: 'GIRL', type: 'typing', isOpposite: true },
    { q: 'ماذا يوجد في الكوب؟ اكتب الكلمة:', display: '🥛', word: 'MILK', answer: 'MILK', type: 'typing' },
    { q: 'اكتب الكلمة:', display: '🌳', answer: 'TREE', type: 'typing' },
    { q: 'رتب: (likes / She / apples)', display: '🍎', isScrambled: true, options: ['She likes apples', 'Apples likes She', 'Likes She apples', 'She apples likes'], answer: 'She likes apples', type: 'choice' },
    { q: 'اكتب جمع كلمة "Cat":', display: '🐱🐱', answer: 'CATS', type: 'typing' },
    { q: 'اكتب الكلمة:', display: '📦', answer: 'BOX', type: 'typing' }
  ],

  // Section F: Vocabulary & Grammar (Original + New = ~40)
  sectionF: [
    { q: 'اختر الصحيح: "She ___ a student."', display: '', options: ['am', 'is', 'are', 'be'], answer: 'is', type: 'choice' },
    { q: 'اختر الصحيح: "I ___ hungry."', display: '', options: ['am', 'is', 'are', 'be'], answer: 'am', type: 'choice' },
    { q: 'اختر الصحيح: "They ___ playing."', display: '', options: ['am', 'is', 'are', 'be'], answer: 'are', type: 'choice' },
    { q: 'ما جمع كلمة "Cat"؟', display: '🐱🐱', options: ['Cats', 'Cates', 'Caties', 'Catss'], answer: 'Cats', type: 'choice' },
    { q: 'اختر الصحيح: "___ is your name?"', display: '', options: ['Who', 'What', 'Where', 'When'], answer: 'What', type: 'choice' },
    { q: 'اختر: "This is ___ book." (يخصني)', display: '', options: ['my', 'your', 'his', 'her'], answer: 'my', type: 'choice' },
    { q: 'اختر: "He ___ to school every day."', display: '', options: ['go', 'goes', 'going', 'gone'], answer: 'goes', type: 'choice' },
    { q: 'ما جمع كلمة "Dog"؟', display: '🐕🐕', options: ['Dogs', 'Doges', 'Dogies', 'Dogss'], answer: 'Dogs', type: 'choice' },
    { q: 'اختر حرف "a" أو "an" الصحيح: ___ elephant', display: '🐘', options: ['a', 'an'], answer: 'an', type: 'choice' },
    { q: 'اختر: "We ___ students."', display: '', options: ['am', 'is', 'are', 'be'], answer: 'are', type: 'choice' },
    { q: 'أي كلمة هي فعل (Verb)؟', display: '', options: ['Run', 'Red', 'Rabbit', 'Room'], answer: 'Run', type: 'choice' },
    { q: 'اختر الضمير (Pronoun) الصحيح: "___ is my sister."', display: '👩', options: ['He', 'She', 'It', 'They'], answer: 'She', type: 'choice' },
    { q: 'أكمل: "Do you like ice cream?" - "Yes, I ___."', display: '🍦', options: ['do', 'does', 'did', 'am'], answer: 'do', type: 'choice' },
    // New Questions Section F
    { q: 'اختر الصحيح: "He ___ happy."', display: '', options: ['is', 'am', 'are', 'be'], answer: 'is', type: 'choice' },
    { q: 'اختر: "___ old are you?"', display: '', options: ['How', 'What', 'Who', 'When'], answer: 'How', type: 'choice' },
    { q: 'ما جمع كلمة "Box"?', display: '📦📦', options: ['Boxs', 'Boxes', 'Boxies', 'Box'], answer: 'Boxes', type: 'choice' },
    { q: 'اختر: "That is ___ apple."', display: '', options: ['a', 'an', 'two', 'many'], answer: 'an', type: 'choice' },
    { q: 'اختر الصحيح: "We ___ friends."', display: '', options: ['is', 'am', 'are', 'be'], answer: 'are', type: 'choice' },
    { q: 'اختر الضمير: "___ is a doctor." (رجل)', display: '👨‍⚕️', options: ['He', 'She', 'It', 'They'], answer: 'He', type: 'choice' },
    { q: 'أكمل: "Where ___ you form?"', display: '', options: ['is', 'am', 'are', 'be'], answer: 'are', type: 'choice' },
    { q: 'اختر: "___ is that?" - "It is a car."', display: '', options: ['What', 'Who', 'Where', 'How'], answer: 'What', type: 'choice' },
    { q: 'أي كلمة هي اسم (Noun)؟', display: '', options: ['Run', 'Big', 'Cat', 'Eat'], answer: 'Cat', type: 'choice' },
    { q: 'ما جمع كلمة "Man"?', display: '👨👨', options: ['Mans', 'Men', 'Manes', 'Mens'], answer: 'Men', type: 'choice' },
    { q: 'اختر: "I have ___ red pen."', display: '', options: ['a', 'an', 'two', 'many'], answer: 'a', type: 'choice' },
    { q: 'اختر: "She ___ breakfast at 7 AM."', display: '', options: ['eat', 'eats', 'eating', 'ate'], answer: 'eats', type: 'choice' },
    { q: 'اختر الملكية: "This is ___ car." (يخصه)', display: '', options: ['his', 'her', 'my', 'your'], answer: 'his', type: 'choice' },
    { q: 'اختر: "___ you speak English?"', display: '', options: ['Do', 'Does', 'Is', 'Are'], answer: 'Do', type: 'choice' },
    { q: 'ما عكس "Big"?', display: '', options: ['Small', 'Tall', 'Fat', 'Long'], answer: 'Small', type: 'choice' },
    { q: 'اختر: "They ___ not at home."', display: '', options: ['is', 'are', 'am', 'be'], answer: 'are', type: 'choice' },
    { q: 'أكمل: "___ is your teacher?"', display: '', options: ['Who', 'What', 'When', 'Why'], answer: 'Who', type: 'choice' },
    { q: 'أي كلمة هي صفة (Adjective)؟', display: '', options: ['Boy', 'Run', 'Happy', 'Apple'], answer: 'Happy', type: 'choice' },
    { q: 'اختر: "___ is a pen."', display: '🖊️', options: ['This', 'These', 'Those', 'They'], answer: 'This', type: 'choice' },
    { q: 'اختر الصحيح: "I ___ playing football now."', display: '', options: ['am', 'is', 'are', 'do'], answer: 'am', type: 'choice' },
    { q: 'ما جمع كلمة "Foot"?', display: '🦶🦶', options: ['Foots', 'Feet', 'Feets', 'Footes'], answer: 'Feet', type: 'choice' },
    // New Vocabulary & Comprehension Questions
    { q: 'What do you use to write your homework?', options: ['Pencil', 'Eraser', 'Ruler', 'Book'], answer: 'Pencil', type: 'choice' },
    { q: 'Where do you go to eat lunch at school?', options: ['Library', 'Cafeteria', 'Gym', 'Classroom'], answer: 'Cafeteria', type: 'choice' },
    { q: 'Which subject do you learn about numbers?', options: ['Science', 'Mathematics', 'History', 'Art'], answer: 'Mathematics', type: 'choice' },
    { q: 'What do you need to study in the library?', options: ['Books', 'Toys', 'Snacks', 'Music'], answer: 'Books', type: 'choice' },
    { q: 'Where do students gather before classes start?', options: ['Hallway', 'Playground', 'Assembly area', 'Office'], answer: 'Assembly area', type: 'choice' },
    { q: 'What do you use to carry your books?', options: ['Backpack', 'Folder', 'Notebook', 'Pocket'], answer: 'Backpack', type: 'choice' },
    { q: 'What activity can you participate in after school?', options: ['Sports', 'Sleeping', 'Eating', 'Nothing'], answer: 'Sports', type: 'choice' },
    { q: 'What device does the teacher use to show lessons?', options: ['Projector', 'Calculator', 'Phone', 'Radio'], answer: 'Projector', type: 'choice' },
    { q: 'What do you need for tests?', options: ['Test paper', 'Pencil case', 'Backpack', 'Toy'], answer: 'Test paper', type: 'choice' },
    { q: 'Where do you learn about arts?', options: ['Art room', 'Science lab', 'Gym', 'Library'], answer: 'Art room', type: 'choice' },
    { q: 'How would you describe a tall person?', options: ['Short', 'Medium', 'Tall', 'Fat'], answer: 'Tall', type: 'choice' },
    { q: 'What word describes a friendly person?', options: ['Rude', 'Kind', 'Shy', 'Angry'], answer: 'Kind', type: 'choice' },
    { q: 'How would you describe someone wearing glasses?', options: ['Glasses', 'Hat', 'Scarf', 'Boots'], answer: 'Glasses', type: 'choice' },
    { q: 'What word describes a smart person?', options: ['Clever', 'Silly', 'Lazy', 'Slow'], answer: 'Clever', type: 'choice' },
    { q: 'How would you describe someone with brown hair?', options: ['Blonde', 'Black', 'Brown', 'Red'], answer: 'Brown', type: 'choice' },
    { q: 'What word describes an active person?', options: ['Lazy', 'Energetic', 'Tired', 'Bored'], answer: 'Energetic', type: 'choice' },
    { q: 'How would you describe someone who is smiling?', options: ['Happy', 'Sad', 'Angry', 'Scared'], answer: 'Happy', type: 'choice' },
    { q: 'What word describes someone who cares about fashion?', options: ['Stylish', 'Messy', 'Casual', 'Old'], answer: 'Stylish', type: 'choice' },
    { q: 'How would you describe someone who loves to read?', options: ['Reader', 'Writer', 'Speaker', 'Listener'], answer: 'Reader', type: 'choice' },
    { q: 'What word describes an ambitious person?', options: ['Unmotivated', 'Driven', 'Content', 'Lazy'], answer: 'Driven', type: 'choice' },
    { q: 'What do you wear in winter?', options: ['T-shirt', 'Coat', 'Shorts', 'Sandals'], answer: 'Coat', type: 'choice' },
    { q: 'What is a common summer clothing item?', options: ['Sweater', 'Dress', 'Jacket', 'Scarf'], answer: 'Dress', type: 'choice' },
    { q: 'What do you wear on your feet?', options: ['Socks', 'Shoes', 'Gloves', 'Hat'], answer: 'Shoes', type: 'choice' },
    { q: 'What type of clothing do students wear at school?', options: ['Casual clothes', 'Uniform', 'Pajamas', 'Swimsuit'], answer: 'Uniform', type: 'choice' },
    { q: 'What do you need to protect your head from the sun?', options: ['Scarf', 'Hat', 'Beanie', 'Boots'], answer: 'Hat', type: 'choice' },
    { q: 'What do you wear to a party?', options: ['Formal dress', 'Sportswear', 'Pajamas', 'Uniform'], answer: 'Formal dress', type: 'choice' },
    { q: 'What do you wear at home?', options: ['Suit', 'Pajamas', 'Uniform', 'Coat'], answer: 'Pajamas', type: 'choice' },
    { q: 'What type of clothing do athletes wear?', options: ['Sportswear', 'Formal wear', 'Casual clothes', 'Pajamas'], answer: 'Sportswear', type: 'choice' },
    { q: 'What do you need in cold weather?', options: ['Mittens', 'Sandals', 'Flip-flops', 'Shorts'], answer: 'Mittens', type: 'choice' },
    { q: 'What do people wear for formal occasions?', options: ['Casual wear', 'Suit or dress', 'Gym clothes', 'Pajamas'], answer: 'Suit or dress', type: 'choice' },
    { q: 'What subject do you study to learn about nature?', options: ['Mathematics', 'Science', 'History', 'Art'], answer: 'Science', type: 'choice' },
    { q: 'In which classroom do you learn about past events?', options: ['History class', 'Math class', 'Art class', 'Gym'], answer: 'History class', type: 'choice' },
    { q: 'What subject involves learning languages?', options: ['Literature', 'Language Arts', 'Physical Education', 'Science'], answer: 'Language Arts', type: 'choice' },
    { q: 'In which classroom do you study numbers?', options: ['Science lab', 'Math classroom', 'Art room', 'Gym'], answer: 'Math classroom', type: 'choice' },
    { q: 'What subject relates to creativity and expression?', options: ['Art', 'Math', 'History', 'Science'], answer: 'Art', type: 'choice' },
    { q: 'In which classroom do you learn about maps and countries?', options: ['Geography class', 'Science class', 'Music class', 'Math class'], answer: 'Geography class', type: 'choice' },
    { q: 'What subject teaches you about computers?', options: ['Technology', 'History', 'Physical Education', 'Art'], answer: 'Technology', type: 'choice' },
    { q: 'In which classroom do you learn about physical fitness?', options: ['Gym', 'Science lab', 'Library', 'Art room'], answer: 'Gym', type: 'choice' },
    { q: 'What subject teaches you about ethics and values?', options: ['Social Studies', 'Mathematics', 'Art', 'Science'], answer: 'Social Studies', type: 'choice' },
    { q: 'In which classroom do you study chemical reactions?', options: ['Chemistry lab', 'History class', 'Math classroom', 'Gym'], answer: 'Chemistry lab', type: 'choice' },
    { q: 'أكمل الجملة: To write my notes during the lesson, I always use a ___ and a notebook.', options: ['chair', 'pen', 'window', 'bag'], answer: 'pen', type: 'choice' },
    { q: 'أكمل الجملة: The teacher writes the lesson on the large white ___ at the front of the classroom.', options: ['desk', 'floor', 'board', 'poster'], answer: 'board', type: 'choice' },
    { q: 'أكمل الجملة: My favorite ___ at school is playing football with my friends during the break.', options: ['subject', 'rule', 'activity', 'uniform'], answer: 'activity', type: 'choice' },
    { q: 'أكمل الجملة: My best friend always helps me when I have a problem. He is a very ___ and loyal person.', options: ['tall', 'funny', 'kind', 'quiet'], answer: 'kind', type: 'choice' },
    { q: 'أكمل الجملة: A person who loves to tell jokes and make everyone laugh is considered ___.', options: ['serious', 'humorous', 'shy', 'short'], answer: 'humorous', type: 'choice' },
    { q: 'أكمل الجملة: My sister has long, curly brown ___ and beautiful green eyes.', options: ['hair', 'hands', 'clothes', 'height'], answer: 'hair', type: 'choice' },
    { q: 'أكمل الجملة: In many schools, students are required to wear a specific ___, which often includes a blazer and a tie.', options: ['costume', 'uniform', 'outfit', 'dress'], answer: 'uniform', type: 'choice' },
    { q: 'أكمل الجملة: When it is very cold and snowy outside, you should wear a warm ___, a scarf, and gloves to stay warm.', options: ['t-shirt', 'shorts', 'coat', 'swimsuit'], answer: 'coat', type: 'choice' },
    { q: 'أكمل الجملة: She loves wearing bright red, yellow, and orange. She prefers ___ clothes.', options: ['muted', 'dark', 'formal', 'colorful'], answer: 'colorful', type: 'choice' },
    { q: 'أكمل الجملة: If you enjoy learning about historical events and the past, your favorite ___ is probably History.', options: ['classroom', 'subject', 'experiment', 'sport'], answer: 'subject', type: 'choice' },
    { q: 'أكمل الجملة: To conduct a science experiment with chemicals and equipment, students must go to the ___.', options: ['library', 'gymnasium', 'laboratory', 'cafeteria'], answer: 'laboratory', type: 'choice' },
    { q: 'أكمل الجملة: If you need to borrow a book or study in a very quiet place, the best place to go is the school ___.', options: ['playground', 'office', 'library', 'lab'], answer: 'library', type: 'choice' },
    // Let's Go 5 - Second Set (New Questions)
    { q: 'What is the bracelet made ______?', display: '', options: ['of', 'from'], answer: 'of', type: 'choice' },
    { q: 'The table is made of ______.', display: '', options: ['wood', 'glass'], answer: 'wood', type: 'choice' },
    { q: 'Which one is ______, the silk or the cotton?', display: '', options: ['softer', 'softest'], answer: 'softer', type: 'choice' },
    { q: 'Is the metal ring ______ than the gold one?', display: '', options: ['heavyer', 'heavier'], answer: 'heavier', type: 'choice' },
    { q: 'What ______ she doing when it started to rain?', display: '', options: ['was', 'is'], answer: 'was', type: 'choice' },
    { q: 'They ______ playing baseball when I saw them.', display: '', options: ['were', 'was'], answer: 'were', type: 'choice' },
    { q: 'Which animal is the ______ dangerous?', display: '', options: ['more', 'most'], answer: 'most', type: 'choice' },
    { q: 'A shark is ______ dangerous than a dolphin.', display: '', options: ['more', 'most'], answer: 'more', type: 'choice' },
    { q: 'Have you ______ been to a circus?', display: '', options: ['ever', 'never'], answer: 'ever', type: 'choice' },
    { q: 'No, I have ______ seen a whale.', display: '', options: ['never', 'ever'], answer: 'never', type: 'choice' },
    { q: 'She has ______ to Egypt twice.', display: '', options: ['been', 'be'], answer: 'been', type: 'choice' },
    { q: 'I ______ never ridden a camel.', display: '', options: ['have', 'has'], answer: 'have', type: 'choice' },
    { q: 'He ______ never eaten sushi.', display: '', options: ['has', 'have'], answer: 'has', type: 'choice' },
    { q: 'The shirt is ______ expensive than the hat.', display: '', options: ['less', 'least'], answer: 'less', type: 'choice' },
    { q: 'This is the ______ expensive watch in the shop.', display: '', options: ['least', 'less'], answer: 'least', type: 'choice' },
    { q: 'What ______ you going to be when you grow up?', display: '', options: ['are', 'will'], answer: 'are', type: 'choice' },
    { q: 'I want to ______ a flight attendant.', display: '', options: ['be', 'am'], answer: 'be', type: 'choice' },
    { q: 'Does she want to be a ______?', display: '', options: ['detective', 'detect'], answer: 'detective', type: 'choice' },
    { q: 'He ______ like to be a scientist.', display: '', options: ['would', 'will'], answer: 'would', type: 'choice' },
    { q: 'What ______ they like to do?', display: '', options: ['would', 'are'], answer: 'would', type: 'choice' },
    { q: 'The slippers ______ soft.', display: '', options: ['feel', 'tastes'], answer: 'feel', type: 'choice' },
    { q: 'The perfume ______ like roses.', display: '', options: ['smells', 'sounds'], answer: 'smells', type: 'choice' },
    { q: 'This pillow feels ______.', display: '', options: ['hard', 'soft'], answer: 'soft', type: 'choice' },
    { q: 'Does the cake ______ sweet?', display: '', options: ['taste', 'tastes'], answer: 'taste', type: 'choice' },
    { q: 'The rainbow ______ beautiful.', display: '', options: ['looks', 'feels'], answer: 'looks', type: 'choice' },
    { q: 'Where ______ they yesterday?', display: '', options: ['were', 'was'], answer: 'were', type: 'choice' },
    { q: 'He was ______ the park at 10:00.', display: '', options: ['at', 'on'], answer: 'at', type: 'choice' },
    { q: 'We were ______ a movie last night.', display: '', options: ['watching', 'watch'], answer: 'watching', type: 'choice' },
    { q: 'They ______ at school this morning.', display: '', options: ['weren\'t', 'wasn\'t'], answer: 'weren\'t', type: 'choice' },
    { q: 'Was she ______ the library?', display: '', options: ['in', 'on'], answer: 'in', type: 'choice' },
    { q: 'How ______ do you go swimming?', display: '', options: ['often', 'many'], answer: 'often', type: 'choice' },
    { q: 'I ______ go swimming.', display: '', options: ['sometimes', 'twice'], answer: 'sometimes', type: 'choice' },
    { q: 'She ______ plays tennis.', display: '', options: ['always', "once"], answer: 'always', type: 'choice' },
    { q: 'He goes to the gym ______ a week.', display: '', options: ['twice', 'two'], answer: 'twice', type: 'choice' },
    { q: 'They go to the cinema ______ a month.', display: '', options: ['once', 'one'], answer: 'once', type: 'choice' },
    { q: 'Which is ______, the mountain or the hill?', display: '', options: ['higher', 'highest'], answer: 'higher', type: 'choice' },
    { q: 'Mount Everest is the ______ mountain.', display: '', options: ['highest', 'higher'], answer: 'highest', type: 'choice' },
    { q: 'The Pacific Ocean is the ______ ocean.', display: '', options: ['deepest', 'deeper'], answer: 'deepest', type: 'choice' },
    { q: 'Is the Nile ______ than the Amazon?', display: '', options: ['longer', 'longest'], answer: 'longer', type: 'choice' },
    { q: 'Which city is the ______?', display: '', options: ['biggest', 'bigger'], answer: 'biggest', type: 'choice' },
    { q: 'I\'m ______ to go camping.', display: '', options: ['going', 'will'], answer: 'going', type: 'choice' },
    { q: 'He\'s going to ______ a tent.', display: '', options: ['bring', 'brought'], answer: 'bring', type: 'choice' },
    { q: 'Are they going to ______ a campfire?', display: '', options: ['build', 'building'], answer: 'build', type: 'choice' },
    { q: 'She ______ going to go fishing.', display: '', options: ['is', 'are'], answer: 'is', type: 'choice' },
    { q: 'We ______ going to sleep in a sleeping bag.', display: '', options: ['are', 'am'], answer: 'are', type: 'choice' },
    { q: 'What ______ you do yesterday?', display: '', options: ['did', 'do'], answer: 'did', type: 'choice' },
    { q: 'I ______ my homework last night.', display: '', options: ['finished', 'finish'], answer: 'finished', type: 'choice' },
    { q: 'Did he ______ the window?', display: '', options: ['close', 'closed'], answer: 'close', type: 'choice' },
    { q: 'They ______ at the party last Friday.', display: '', options: ['were', 'was'], answer: 'were', type: 'choice' },
    { q: 'She ______ to the store an hour ago.', display: '', options: ['went', 'goes'], answer: 'went', type: 'choice' },
    // Let's Go 5 Final Exam Questions
    { q: 'How ______ cans of soda are there?', display: '', options: ['many', 'much'], answer: 'many', type: 'choice' },
    { q: 'How ______ rice is there?', display: '', options: ['many', 'much'], answer: 'much', type: 'choice' },
    { q: 'There are ______ cookies.', display: '', options: ['a few', 'a little'], answer: 'a few', type: 'choice' },
    { q: 'There is ______ tea.', display: '', options: ['a few', 'a little'], answer: 'a little', type: 'choice' },
    { q: '______ there any sandwiches on the plate?', display: '', options: ['Is', 'Are'], answer: 'Are', type: 'choice' },
    { q: 'There ______ a lot of water in the bottle.', display: '', options: ['is', 'are'], answer: 'is', type: 'choice' },
    { q: 'How many ______ of juice are there?', display: '', options: ['cartons', 'pieces'], answer: 'cartons', type: 'choice' },
    { q: 'There is a ______ of pizza.', display: '', options: ['can', 'piece'], answer: 'piece', type: 'choice' },
    { q: 'How many ______ are there?', display: '', options: ['banana', 'bananas'], answer: 'bananas', type: 'choice' },
    { q: 'Is there ______ soda in the fridge?', display: '', options: ['a lot of', 'many'], answer: 'a lot of', type: 'choice' },
    { q: 'Is a gazelle ______ fast as a zebra?', display: '', options: ['as', 'than'], answer: 'as', type: 'choice' },
    { q: 'A cheetah is ______ than a wolf.', display: '', options: ['fast', 'faster'], answer: 'faster', type: 'choice' },
    { q: 'Which animal is the ______?', display: '', options: ['fastest', 'faster'], answer: 'fastest', type: 'choice' },
    { q: 'A turtle is ______ than a gazelle.', display: '', options: ['slow', 'slower'], answer: 'slower', type: 'choice' },
    { q: 'Is a wolf as fast as a skunk?', display: '', options: ['Yes, it is', 'No, it isn\'t'], answer: 'No, it isn\'t', type: 'choice' },
    { q: 'The elephant is the ______ animal.', display: '', options: ['larger', 'largest'], answer: 'largest', type: 'choice' },
    { q: 'Are the shoes ______ expensive than the socks?', display: '', options: ['more', 'most'], answer: 'more', type: 'choice' },
    { q: 'Which class is the ______?', display: '', options: ['easier', 'easiest'], answer: 'easiest', type: 'choice' },
    { q: 'A polar bear is ______ fast as a rhinoceros.', display: '', options: ['as', 'than'], answer: 'as', type: 'choice' },
    { q: 'Which one is ______ delicious?', display: '', options: ['more', 'most'], answer: 'more', type: 'choice' },
    { q: 'What ______ they do last weekend?', display: '', options: ['do', 'did'], answer: 'did', type: 'choice' },
    { q: 'He ______ for a walk yesterday.', display: '', options: ['go', 'went'], answer: 'went', type: 'choice' },
    { q: 'She ______ pictures last Sunday.', display: '', options: ['was taking', 'takes'], answer: 'was taking', type: 'choice' },
    { q: 'How ______ your weekend?', display: '', options: ['is', 'was'], answer: 'was', type: 'choice' },
    { q: 'They went ______ last weekend.', display: '', options: ['bowling', 'bowl'], answer: 'bowling', type: 'choice' },
    { q: 'Did he ______ up the heat?', display: '', options: ['turn', 'turned'], answer: 'turn', type: 'choice' },
    { q: 'Where ______ he this morning?', display: '', options: ['is', 'was'], answer: 'was', type: 'choice' },
    { q: 'We ______ some jam yesterday.', display: '', options: ['make', 'made'], answer: 'made', type: 'choice' },
    { q: 'I ______ my friend at the park yesterday.', display: '', options: ['meet', 'met'], answer: 'met', type: 'choice' },
    { q: 'Did you take ______ your shoes?', display: '', options: ['off', 'on'], answer: 'off', type: 'choice' },
    { q: 'What do you think she ______ be?', display: '', options: ['will', 'is'], answer: 'will', type: 'choice' },
    { q: 'I think he’ll be a ______ stylist.', display: '', options: ['hair', 'hairy'], answer: 'hair', type: 'choice' },
    { q: 'What ______ she do next?', display: '', options: ['will', 'does'], answer: 'will', type: 'choice' },
    { q: 'She’ll ______ mop the floor.', display: '', options: ['probably', 'will'], answer: 'probably', type: 'choice' },
    { q: 'He wants to be an ______.', display: '', options: ['architect', 'architecture'], answer: 'architect', type: 'choice' },
    { q: 'What ______ he going to do tonight?', display: '', options: ['is', 'will'], answer: 'is', type: 'choice' },
    { q: 'He’s going to ______ his room.', display: '', options: ['clean', 'cleaned'], answer: 'clean', type: 'choice' },
    { q: 'When’s she going to ______ backpacking?', display: '', options: ['go', 'goes'], answer: 'go', type: 'choice' },
    { q: 'You’ll be a movie ______.', display: '', options: ['director', 'direct'], answer: 'director', type: 'choice' },
    { q: 'I ______ he\'ll be a tennis player.', display: '', options: ['think', 'thinks'], answer: 'think', type: 'choice' },
    { q: 'How does the lemon ______?', display: '', options: ['taste', 'tastes'], answer: 'taste', type: 'choice' },
    { q: 'It tastes ______.', display: '', options: ['sour', 'sweet'], answer: 'sour', type: 'choice' },
    { q: 'The garbage ______ bad.', display: '', options: ['smells', 'looks'], answer: 'smells', type: 'choice' },
    { q: 'Why do you like ______? Because I like skiing.', display: '', options: ['winter', 'summer'], answer: 'winter', type: 'choice' },
    { q: 'She usually rides a bike ______.', display: '', options: ['carefully', 'careful'], answer: 'carefully', type: 'choice' },
    { q: 'Does he usually talk ______?', display: '', options: ['loudly', 'loud'], answer: 'loudly', type: 'choice' },
    { q: 'The music ______ great!', display: '', options: ['sounds', 'tastes'], answer: 'sounds', type: 'choice' },
    { q: 'Have you ever ______ sushi?', display: '', options: ['eat', 'eaten'], answer: 'eaten', type: 'choice' },
    { q: 'Algebra is ______ to me.', display: '', options: ['confusing', 'confused'], answer: 'confusing', type: 'choice' },
    { q: 'What does your brother ______ like?', display: '', options: ['look', 'looks'], answer: 'look', type: 'choice' },
    // Let's Go 6 Final Exam Questions
    { q: 'What\'s the ______ mountain in the world?', display: '', options: ['highest', 'high'], answer: 'highest', type: 'choice' },
    { q: 'Computers are ______ in many factories.', display: '', options: ['use', 'used'], answer: 'used', type: 'choice' },
    { q: 'Paper is made ______ wood.', display: '', options: ['from', 'of'], answer: 'from', type: 'choice' },
    { q: 'I have ______ playing tennis for two hours.', display: '', options: ['been', 'be'], answer: 'been', type: 'choice' },
    { q: 'She has been ______ since 9 o\'clock.', display: '', options: ['studied', 'studying'], answer: 'studying', type: 'choice' },
    { q: 'How ______ have you been collecting stamps?', display: '', options: ['long', 'often'], answer: 'long', type: 'choice' },
    { q: 'I\'ve been collecting them ______ three years.', display: '', options: ['for', 'since'], answer: 'for', type: 'choice' },
    { q: 'If I ______ a lottery, I would buy a car.', display: '', options: ['won', 'win'], answer: 'won', type: 'choice' },
    { q: 'If he ______ rich, he would travel the world.', display: '', options: ['were', 'is'], answer: 'were', type: 'choice' },
    { q: 'Where ______ you go if you could go anywhere?', display: '', options: ['would', 'will'], answer: 'would', type: 'choice' },
    { q: 'The pyramids ______ built by Egyptians.', display: '', options: ['were', 'was'], answer: 'were', type: 'choice' },
    { q: 'Is cotton ______ in Egypt?', display: '', options: ['grown', 'grow'], answer: 'grown', type: 'choice' },
    { q: 'What is the ______ car in the world?', display: '', options: ['fastest', 'faster'], answer: 'fastest', type: 'choice' },
    { q: 'This book was ______ by a famous author.', display: '', options: ['written', 'wrote'], answer: 'written', type: 'choice' },
    { q: 'She ______ like to be a journalist.', display: '', options: ['would', 'will'], answer: 'would', type: 'choice' },
    { q: 'I\'ve been waiting ______ this morning.', display: '', options: ['since', 'for'], answer: 'since', type: 'choice' },
    { q: 'How long ______ it been raining?', display: '', options: ['has', 'have'], answer: 'has', type: 'choice' },
    { q: 'Gold is ______ than silver.', display: '', options: ['more expensive', 'most expensive'], answer: 'more expensive', type: 'choice' },
    { q: 'The telephone was ______ by Bell.', display: '', options: ['invented', 'invent'], answer: 'invented', type: 'choice' },
    { q: 'What ______ you doing when the lights went out?', display: '', options: ['were', 'was'], answer: 'were', type: 'choice' },
    { q: 'I ______ eating dinner at that time.', display: '', options: ['was', 'were'], answer: 'was', type: 'choice' },
    { q: 'She ______ to the zoo last week.', display: '', options: ['went', 'gone'], answer: 'went', type: 'choice' },
    { q: 'Have you ______ seen a koala?', display: '', options: ['ever', 'never'], answer: 'ever', type: 'choice' },
    { q: 'I have ______ been to Japan.', display: '', options: ['never', 'ever'], answer: 'never', type: 'choice' },
    { q: 'If I ______ you, I would study harder.', display: '', options: ['were', 'am'], answer: 'were', type: 'choice' },
    { q: 'This cake ______ delicious.', display: '', options: ['tastes', 'sounds'], answer: 'tastes', type: 'choice' },
    { q: 'The music ______ too loud.', display: '', options: ['sounds', 'looks'], answer: 'sounds', type: 'choice' },
    { q: 'Which is ______, the sun or the moon?', display: '', options: ['hotter', 'hottest'], answer: 'hotter', type: 'choice' },
    { q: 'Cars are ______ in Japan.', display: '', options: ['manufactured', 'manufacture'], answer: 'manufactured', type: 'choice' },
    { q: 'The bridge was ______ in 1990.', display: '', options: ['completed', 'complete'], answer: 'completed', type: 'choice' },
    { q: 'What ______ you like to be?', display: '', options: ['would', 'do'], answer: 'would', type: 'choice' },
    { q: 'I want to be ______ astronaut.', display: '', options: ['an', 'a'], answer: 'an', type: 'choice' },
    { q: 'He wants to be ______ pilot.', display: '', options: ['a', 'an'], answer: 'a', type: 'choice' },
    { q: 'She has ______ abroad many times.', display: '', options: ['traveled', 'travel'], answer: 'traveled', type: 'choice' },
    { q: 'They ______ playing soccer for an hour.', display: '', options: ['have been', 'has been'], answer: 'have been', type: 'choice' },
    { q: 'I ______ been living here for ten years.', display: '', options: ['have', 'has'], answer: 'have', type: 'choice' },
    { q: 'She ______ been teaching since 2010.', display: '', options: ['has', 'have'], answer: 'has', type: 'choice' },
    { q: 'Is coffee ______ in Brazil?', display: '', options: ['produced', 'produce'], answer: 'produced', type: 'choice' },
    { q: 'Cheese is ______ from milk.', display: '', options: ['made', 'make'], answer: 'made', type: 'choice' },
    { q: 'This watch is made ______ gold.', display: '', options: ['of', 'from'], answer: 'of', type: 'choice' },
    { q: 'How long has he ______ working?', display: '', options: ['been', 'be'], answer: 'been', type: 'choice' },
    { q: 'It ______ like it\'s going to rain.', display: '', options: ['looks', 'tastes'], answer: 'looks', type: 'choice' },
    { q: 'The silk ______ very soft.', display: '', options: ['feels', 'smells'], answer: 'feels', type: 'choice' },
    { q: 'The flowers ______ wonderful.', display: '', options: ['smell', 'taste'], answer: 'smell', type: 'choice' },
    { q: 'If she ______ a bird, she would fly.', display: '', options: ['were', 'was'], answer: 'were', type: 'choice' },
    { q: 'Would you ______ a space shuttle?', display: '', options: ['fly', 'flew'], answer: 'fly', type: 'choice' },
    { q: 'I ______ buy a big house if I had money.', display: '', options: ['would', 'will'], answer: 'would', type: 'choice' },
    { q: 'The statue was ______ by a sculptor.', display: '', options: ['carved', 'carve'], answer: 'carved', type: 'choice' },
    { q: 'What ______ the most popular sport?', display: '', options: ['is', 'are'], answer: 'is', type: 'choice' },
    { q: 'Who ______ the light bulb?', display: '', options: ['invented', 'invent'], answer: 'invented', type: 'choice' },
    { q: 'English is ______ all over the world.', display: '', options: ['spoken', 'speak'], answer: 'spoken', type: 'choice' },
    { q: 'How much ______ that laptop cost?', display: '', options: ['does', 'is'], answer: 'does', type: 'choice' },
    { q: 'They ______ sleeping when I arrived.', display: '', options: ['were', 'was'], answer: 'were', type: 'choice' },
    { q: 'She ______ her homework already.', display: '', options: ['has done', 'did'], answer: 'has done', type: 'choice' },
    { q: 'I ______ my keys yesterday.', display: '', options: ['lost', 'lose'], answer: 'lost', type: 'choice' },
    { q: 'He ______ been a doctor for 20 years.', display: '', options: ['has', 'have'], answer: 'has', type: 'choice' },
    { q: 'We ______ been friends since 1st grade.', display: '', options: ['have', 'has'], answer: 'have', type: 'choice' },
    { q: 'The movie was ______ by Spielberg.', display: '', options: ['directed', 'direct'], answer: 'directed', type: 'choice' },
    { q: 'Is the Nile ______ than the Amazon?', display: '', options: ['longer', 'longest'], answer: 'longer', type: 'choice' },
    { q: 'That is the ______ interesting book.', display: '', options: ['most', 'more'], answer: 'most', type: 'choice' },
    { q: 'What is it ______ of?', display: '', options: ['made', 'make'], answer: 'made', type: 'choice' },
    { q: 'It\'s made ______ plastic.', display: '', options: ['of', 'from'], answer: 'of', type: 'choice' },
    { q: 'The pizza ______ great.', display: '', options: ['smells', 'sounds'], answer: 'smells', type: 'choice' },
    { q: 'I ______ go to the moon if I could.', display: '', options: ['would', 'will'], answer: 'would', type: 'choice' },
    { q: 'Have you ______ ridden a horse?', display: '', options: ['ever', 'never'], answer: 'ever', type: 'choice' },
    { q: 'I\'ve ______ been to the moon.', display: '', options: ['never', 'ever'], answer: 'never', type: 'choice' },
    { q: 'He ______ been painting the fence.', display: '', options: ['has', 'have'], answer: 'has', type: 'choice' },
    { q: 'They ______ been running for miles.', display: '', options: ['have', 'has'], answer: 'have', type: 'choice' },
    { q: 'If he ______ faster, he would win.', display: '', options: ['ran', 'runs'], answer: 'ran', type: 'choice' },
    { q: 'Where ______ the car parked?', display: '', options: ['was', 'were'], answer: 'was', type: 'choice' },
    { q: 'The window was ______ by the ball.', display: '', options: ['broken', 'broke'], answer: 'broken', type: 'choice' },
    { q: 'Who ______ the race?', display: '', options: ['won', 'win'], answer: 'won', type: 'choice' },
    { q: 'Which ocean is the ______?', display: '', options: ['largest', 'larger'], answer: 'largest', type: 'choice' },
    { q: 'Rice is ______ in Asia.', display: '', options: ['grown', 'grew'], answer: 'grown', type: 'choice' },
    { q: 'The letter was ______ yesterday.', display: '', options: ['sent', 'send'], answer: 'sent', type: 'choice' },
    { q: 'How long ______ you been swimming?', display: '', options: ['have', 'has'], answer: 'have', type: 'choice' },
    { q: 'I ______ been swimming for an hour.', display: '', options: ['have', 'has'], answer: 'have', type: 'choice' },
    { q: 'What ______ you do if you were invisible?', display: '', options: ['would', 'will'], answer: 'would', type: 'choice' },
    { q: 'I ______ travel the world.', display: '', options: ['would', 'will'], answer: 'would', type: 'choice' },
    { q: 'Is the moon ______ than the Earth?', display: '', options: ['smaller', 'smallest'], answer: 'smaller', type: 'choice' },
    { q: 'This song was ______ by Adele.', display: '', options: ['sung', 'sang'], answer: 'sung', type: 'choice' },
    { q: 'The house was ______ last year.', display: '', options: ['painted', 'paint'], answer: 'painted', type: 'choice' },
    { q: 'How long ______ she been dancing?', display: '', options: ['has', 'have'], answer: 'has', type: 'choice' },
    { q: 'She ______ been dancing since 5:00.', display: '', options: ['has', 'have'], answer: 'has', type: 'choice' },
    { q: 'If I ______ wings, I would fly.', display: '', options: ['had', 'have'], answer: 'had', type: 'choice' },
    { q: 'The dinner was ______ by my mom.', display: '', options: ['cooked', 'cook'], answer: 'cooked', type: 'choice' },
    { q: 'Which is ______ expensive, gold or iron?', display: '', options: ['more', 'most'], answer: 'more', type: 'choice' },
    { q: 'The car ______ washed every week.', display: '', options: ['is', 'are'], answer: 'is', type: 'choice' },
    { q: 'Have you ______ flown in a helicopter?', display: '', options: ['ever', 'never'], answer: 'ever', type: 'choice' },
    { q: 'I\'ve ______ tried skydiving.', display: '', options: ['never', 'ever'], answer: 'never', type: 'choice' },
    { q: 'How long ______ they been talking?', display: '', options: ['have', 'has'], answer: 'have', type: 'choice' },
    { q: 'They ______ been talking for hours.', display: '', options: ['have', 'has'], answer: 'have', type: 'choice' },
    { q: 'If it ______ tomorrow, I\'ll stay home.', display: '', options: ['rains', 'rained'], answer: 'rains', type: 'choice' },
    { q: 'The game ______ played by millions.', display: '', options: ['is', 'are'], answer: 'is', type: 'choice' },
    { q: 'The thief was ______ by the police.', display: '', options: ['caught', 'catch'], answer: 'caught', type: 'choice' },
    { q: 'Which city is ______ crowded?', display: '', options: ['more', 'most'], answer: 'more', type: 'choice' },
    { q: 'I ______ like to be a scientist.', display: '', options: ['would', 'will'], answer: 'would', type: 'choice' },
    { q: 'How ______ water do you drink?', display: '', options: ['much', 'many'], answer: 'much', type: 'choice' },
    { q: 'How ______ friends do you have?', display: '', options: ['many', 'much'], answer: 'many', type: 'choice' },
    { q: 'That movie ______ scary.', display: '', options: ['looks', 'tastes'], answer: 'looks', type: 'choice' },
    // Let's Go 4 Final Exam Questions
    { q: 'Which one is ______? (heavy)', display: '', options: ['heavier', 'heavyest'], answer: 'heavier', type: 'choice' },
    { q: 'The marble is the ______.', display: '', options: ['smallest', 'smaller'], answer: 'smallest', type: 'choice' },
    { q: 'What ______ he do yesterday?', display: '', options: ['did', 'does'], answer: 'did', type: 'choice' },
    { q: 'She ______ a movie last night.', display: '', options: ['watched', 'watch'], answer: 'watched', type: 'choice' },
    { q: 'How ______ do you go to the park?', display: '', options: ['often', 'many'], answer: 'often', type: 'choice' },
    { q: 'I ______ go to the park.', display: '', options: ['sometimes', 'twice'], answer: 'sometimes', type: 'choice' },
    { q: 'He plays the guitar ______.', display: '', options: ['well', 'good'], answer: 'well', type: 'choice' },
    { q: 'She speaks ______.', display: '', options: ['quietly', 'quiet'], answer: 'quietly', type: 'choice' },
    { q: 'Whose ______ are these?', display: '', options: ['shoes', 'shoe'], answer: 'shoes', type: 'choice' },
    { q: 'They are ______.', display: '', options: ['hers', 'her'], answer: 'hers', type: 'choice' },
    { q: 'There is ______ cheese.', display: '', options: ['some', 'many'], answer: 'some', type: 'choice' },
    { q: 'Are there ______ grapes?', display: '', options: ['any', 'a'], answer: 'any', type: 'choice' },
    { q: 'What ______ she want to be?', display: '', options: ['does', 'do'], answer: 'does', type: 'choice' },
    { q: 'She ______ to be a nurse.', display: '', options: ['wants', 'want'], answer: 'wants', type: 'choice' },
    { q: 'What\'s the ______ doing?', display: '', options: ['cook', 'cooking'], answer: 'cook', type: 'choice' },
    { q: 'He\'s ______ a sandwich.', display: '', options: ['making', 'make'], answer: 'making', type: 'choice' },
    { q: 'Where ______ they this morning?', display: '', options: ['were', 'was'], answer: 'were', type: 'choice' },
    { q: 'They ______ at the department store.', display: '', options: ['were', 'was'], answer: 'were', type: 'choice' },
    { q: 'Is the blue car ______ than the red one?', display: '', options: ['faster', 'fastest'], answer: 'faster', type: 'choice' },
    { q: 'The cheetah is the ______ land animal.', display: '', options: ['fastest', 'faster'], answer: 'fastest', type: 'choice' },
    { q: 'Did you ______ a postcard?', display: '', options: ['send', 'sent'], answer: 'send', type: 'choice' },
    { q: 'Yes, I ______ one.', display: '', options: ['sent', 'send'], answer: 'sent', type: 'choice' },
    { q: 'He ______ his homework at 7:00.', display: '', options: ['did', 'do'], answer: 'did', type: 'choice' },
    { q: 'She ______ the violin beautifully.', display: '', options: ['plays', 'play'], answer: 'plays', type: 'choice' },
    { q: 'They walk ______ to school.', display: '', options: ['quickly', 'quick'], answer: 'quickly', type: 'choice' },
    { q: '______ book is this?', display: '', options: ['Whose', 'Who'], answer: 'Whose', type: 'choice' },
    { q: 'It\'s ______.', display: '', options: ['mine', 'my'], answer: 'mine', type: 'choice' },
    { q: 'There ______ any milk in the fridge.', display: '', options: ['isn\'t', 'aren\'t'], answer: 'isn\'t', type: 'choice' },
    { q: 'There ______ some crackers in the box.', display: '', options: ['are', 'is'], answer: 'are', type: 'choice' },
    { q: 'What ______ you do last weekend?', display: '', options: ['did', 'do'], answer: 'did', type: 'choice' },
    { q: 'We ______ a picnic.', display: '', options: ['had', 'have'], answer: 'had', type: 'choice' },
    { q: 'A turtle is ______ than a rabbit.', display: '', options: ['slower', 'slowest'], answer: 'slower', type: 'choice' },
    { q: 'The elephant is the ______.', display: '', options: ['biggest', 'bigger'], answer: 'biggest', type: 'choice' },
    { q: 'Does he ______ to go to the park?', display: '', options: ['want', 'wants'], answer: 'want', type: 'choice' },
    { q: 'Yes, he ______.', display: '', options: ['does', 'do'], answer: 'does', type: 'choice' },
    { q: 'I ______ a cake for my mom.', display: '', options: ['made', 'make'], answer: 'made', type: 'choice' },
    { q: 'How ______ do you brush your teeth?', display: '', options: ['often', 'much'], answer: 'often', type: 'choice' },
    { q: 'I brush them ______ a day.', display: '', options: ['twice', 'two'], answer: 'twice', type: 'choice' },
    { q: 'She ______ a horse last summer.', display: '', options: ['rode', 'ride'], answer: 'rode', type: 'choice' },
    { q: 'They ______ to the beach.', display: '', options: ['went', 'go'], answer: 'went', type: 'choice' },
    { q: 'He is a ______ driver.', display: '', options: ['careful', 'carefully'], answer: 'careval', type: 'choice' },
    { q: 'He drives ______.', display: '', options: ['carefully', 'careful'], answer: 'carefully', type: 'choice' },
    { q: 'Is this ______ bag?', display: '', options: ['your', 'yours'], answer: 'your', type: 'choice' },
    { q: 'No, it\'s ______.', display: '', options: ['his', 'him'], answer: 'his', type: 'choice' },
    { q: 'How ______ water is there?', display: '', options: ['much', 'many'], answer: 'much', type: 'choice' },
    { q: 'How ______ cookies are there?', display: '', options: ['many', 'much'], answer: 'many', type: 'choice' },
    { q: 'Where ______ she yesterday?', display: '', options: ['was', 'were'], answer: 'was', type: 'choice' },
    { q: 'She ______ at the library.', display: '', options: ['was', 'were'], answer: 'was', type: 'choice' },
    { q: 'What ______ they going to do?', display: '', options: ['are', 'is'], answer: 'are', type: 'choice' },
    { q: 'They are ______ to go hiking.', display: '', options: ['going', 'go'], answer: 'going', type: 'choice' },
    { q: 'Which pencil is the ______? (long)', display: '', options: ['longest', 'longer'], answer: 'longest', type: 'choice' },
    { q: 'Is a gazelle ______ than a lion?', display: '', options: ['faster', 'fast'], answer: 'faster', type: 'choice' },
    { q: 'Did he ______ a gift?', display: '', options: ['buy', 'bought'], answer: 'buy', type: 'choice' },
    { q: 'No, he ______.', display: '', options: ['didn\'t', 'doesn\'t'], answer: 'didn\'t', type: 'choice' },
    { q: 'She ______ to music yesterday.', display: '', options: ['listened', 'listen'], answer: 'listened', type: 'choice' },
    { q: 'They ______ pictures in class.', display: '', options: ['drew', 'draw'], answer: 'drew', type: 'choice' },
    { q: 'He writes ______.', display: '', options: ['slowly', 'slow'], answer: 'slowly', type: 'choice' },
    { q: 'You sing ______.', display: '', options: ['beautifully', 'beautiful'], answer: 'beautifully', type: 'choice' },
    { q: 'Are those ______ books?', display: '', options: ['their', 'theirs'], answer: 'their', type: 'choice' },
    { q: 'Yes, they are ______.', display: '', options: ['theirs', 'their'], answer: 'theirs', type: 'choice' },
    { q: 'I want ______ tuna.', display: '', options: ['some', 'a'], answer: 'some', type: 'choice' },
    { q: 'I don\'t want ______ popcorn.', display: '', options: ['any', 'some'], answer: 'any', type: 'choice' },
    { q: 'What ______ you want to be?', display: '', options: ['do', 'does'], answer: 'do', type: 'choice' },
    { q: 'I ______ to be a scientist.', display: '', options: ['want', 'wants'], answer: 'want', type: 'choice' },
    { q: 'He ______ on the phone now.', display: '', options: ['is talking', 'talked'], answer: 'is talking', type: 'choice' },
    { q: 'They ______ TV every night.', display: '', options: ['watch', 'watched'], answer: 'watch', type: 'choice' },
    { q: 'Was he ______ the zoo?', display: '', options: ['at', 'on'], answer: 'at', type: 'choice' },
    { q: 'No, he ______.', display: '', options: ['wasn\'t', 'weren\'t'], answer: 'wasn\'t', type: 'choice' },
    { q: 'The red dress is ______ than the pink one.', display: '', options: ['prettier', 'prettyest'], answer: 'prettier', type: 'choice' },
    { q: 'This is the ______ book in the world.', display: '', options: ['best', 'better'], answer: 'best', type: 'choice' },
    { q: 'What ______ you have for breakfast?', display: '', options: ['did', 'do'], answer: 'did', type: 'choice' },
    { q: 'I ______ eggs and toast.', display: '', options: ['had', 'have'], answer: 'had', type: 'choice' },
    { q: 'She ______ the bed this morning.', display: '', options: ['made', 'make'], answer: 'made', type: 'choice' },
    { q: 'He ______ the piano at the concert.', display: '', options: ['played', 'play'], answer: 'played', type: 'choice' },
    { q: 'They speak English ______.', display: '', options: ['well', 'good'], answer: 'well', type: 'choice' },
    { q: 'Please walk ______.', display: '', options: ['quietly', 'quiet'], answer: 'quietly', type: 'choice' },
    { q: 'Whose ______ is this?', display: '', options: ['jacket', 'jackets'], answer: 'jacket', type: 'choice' },
    { q: 'It\'s ______.', display: '', options: ['ours', 'our'], answer: 'ours', type: 'choice' },
    { q: 'There ______ a lot of salt.', display: '', options: ['is', 'are'], answer: 'is', type: 'choice' },
    { q: 'There ______ many apples.', display: '', options: ['are', 'is'], answer: 'are', type: 'choice' },
    { q: 'How ______ do you go to the movies?', display: '', options: ['often', 'long'], answer: 'often', type: 'choice' },
    { q: 'I go ______ a month.', display: '', options: ['once', 'one'], answer: 'once', type: 'choice' },
    { q: 'He ______ a sandwich for lunch yesterday.', display: '', options: ['ate', 'eat'], answer: 'ate', type: 'choice' },
    { q: 'She ______ a letter to her friend.', display: '', options: ['wrote', 'write'], answer: 'wrote', type: 'choice' },
    { q: 'He is ______ his room.', display: '', options: ['cleaning', 'clean'], answer: 'cleaning', type: 'choice' },
    { q: 'They ______ games in the yard.', display: '', options: ['are playing', 'plays'], answer: 'are playing', type: 'choice' },
    { q: 'Were they ______ the circus?', display: '', options: ['at', 'on'], answer: 'at', type: 'choice' },
    { q: 'Yes, they ______.', display: '', options: ['were', 'was'], answer: 'were', type: 'choice' },
    { q: 'Which mountain is ______? (high)', display: '', options: ['higher', 'high'], answer: 'higher', type: 'choice' },
    { q: 'Mount Everest is the ______.', display: '', options: ['highest', 'higher'], answer: 'highest', type: 'choice' },
    { q: 'Did she ______ any photos?', display: '', options: ['take', 'took'], answer: 'take', type: 'choice' },
    { q: 'Yes, she ______ some.', display: '', options: ['took', 'take'], answer: 'took', type: 'choice' },
    { q: 'I ______ my teeth every morning.', display: '', options: ['brush', 'brushed'], answer: 'brush', type: 'choice' },
    { q: 'She ______ to school by bus.', display: '', options: ['goes', 'go'], answer: 'goes', type: 'choice' },
    { q: 'He talks ______.', display: '', options: ['loudly', 'loud'], answer: 'loudly', type: 'choice' },
    { q: 'They study ______.', display: '', options: ['hard', 'hardly'], answer: 'hard', type: 'choice' },
    { q: 'Whose ______ are these?', display: '', options: ['pencils', 'pencil'], answer: 'pencils', type: 'choice' },
    { q: 'They are ______.', display: '', options: ['yours", "your'], answer: 'yours', type: 'choice' },
    { q: 'Is there ______ juice?', display: '', options: ['any', 'many'], answer: 'any', type: 'choice' },
    { q: 'Yes, there is ______.', display: '', options: ['some', 'any'], answer: 'some', type: 'choice' }
  ]
};
